export const UserActionType ={
    SET_CURRENT_USER:'SET_CURRENT_USER',
    EMAIL_LOGIN_START: 'EMAIL_LOGIN_START',
    GMAIL_LOGIN_START: 'GMAIL_LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE:  'LOGIN_FAILURE',

 
    
};