export const UserActionType ={
    SET_CURRENT_USER:'SET_CURRENT_USER',

    GMAIL_LOGIN_START: 'GMAIL_LOGIN_START',
    GMAIL_LOGIN_SUCCESS: 'GMAIL_LOGIN_SUCCESS',
    GMAIL_LOGIN_FAILURE:  'GMAIL_LOGIN_FAILURE',

    EMAIL_LOGIN_START: 'EMAIL_LOGIN_START',
    EMAIL_LOGIN_SUCCESS: 'EMAIL_LOGIN_SUCCESS',
    EMAIL_LOGIN_FAILURE:  'EMAIL_LOGIN_FAILURE',
};